### ISSUE TITLE
Advanced currency system

### ISSUE THREAD

**Issue by TomPiXX** [MinecraftWars/Gringotts#119]
It would be nice if we could have more currencies (Gold, Emeralds....) and exchange rates.
This would make Gringotts the most flexible economy plugin.

**Comment by jastice** [comment]
Do you mean actual different currencies, where you can't pay with emeralds if the shop requires gold? That's not really practical because the Vault API doesn't support it.

If you mean denominations, where eg 1 emerald = 3 gold bars: Gringotts has that :)
