### ISSUE TITLE
Support for factionUUID

### ISSUE THREAD

**Issue by Kladdkaka** [MinecraftWars/Gringotts#120]
Hello :) My server wants to use this plugin because it looks wonderful! :D However we got a problem, we are using a fork of FactionUUID which is a version of old factions that have been updated with uuid support. And when I try to run Gringotts (latest version 2.4.1) it won't work and also the faction plugin wont work either. 
https://github.com/drtshock/Factions there is the sourcecode for factionUUID :) thanks in advance!

**Comment by jastice** [comment]
It's not straightforward to support multiple factions versions in the same plugin, and I'm not inclined to add support for a version that isn't even freely distributed. It shouldn't be to hard to build a custom version of Gringotts that works with FactionUUID, though. You would only need to adapt the [FactionsHandler|https://github.com/MinecraftWars/Gringotts/blob/master/src/main/java/org/gestern/gringotts/dependency/FactionsHandler.java] a bit. Perhaps replacing with an older version even works.

**Comment by Kladdkaka** [comment]
That's understandable :) I'll try to fix it myself, thanks for the answer!
