### ISSUE TITLE
Bank won't deposit after 99

### ISSUE THREAD

**Issue by Obliviator** [MinecraftWars/Gringotts#125]
Hey man, great plugin and I am using it with Gringotts.
I had Iconomy put I took that out, to try and figure out the issue.

You cannot do /t deposit after the Bank reaches 99

It says You don't have that much.

But I do.... I do have that much. Please help

**Comment by jastice** [comment]
I'm not quite clear what the problem is. Can you provide some example screenshots?

**Comment by Obliviator** [comment]
I use Gringotts, and with that I use Silver Coins from the Lord of the Rings. The penny is 1 Monies, The Dime is 10 Monies, and the Dollar Coin is 100 Monies. 

If I do /t deposit 1-99 it will be fine, but if I try to do /t deposit 100, it will say [Towny] You don't have that much.

I can add any amount, until the bank reaches 99

Using /t The bank says 99, and I cannot add anymore, because is says [Towny] You don't have that much.
![2015-08-06_09 23 20](https://cloud.githubusercontent.com/assets/11671169/9112505/ed10bc7e-3c1c-11e5-9ff3-d42215852709.png)
![2015-08-06_09 23 41](https://cloud.githubusercontent.com/assets/11671169/9112506/ed12d766-3c1c-11e5-9dfa-31b5c1890c71.png)
![2015-08-06_09 23 11](https://cloud.githubusercontent.com/assets/11671169/9112507/ed14ed26-3c1c-11e5-9a98-f5c7dddbccae.png)

**Comment by Obliviator** [comment]
HELP pleeeeease I give a donut for helps

**Comment by jastice** [comment]
Have you created a vault for the town?

**Comment by Obliviator** [comment]
No.... how do I do that

**Comment by jastice** [comment]
Please read the documentation.
