### ISSUE TITLE
emerald reward rarity must be configurable

### ISSUE THREAD

**Issue by meoso** [MinecraftWars/Gringotts#131]
This is a great plugin; however, i deeply believe that emerald reward rarity must be configurable.

They are rewarded too easily.  for example i barely start to kill much and i have already have 23 emeralds.  I would like to have this completely configurable, maybe a setting to set chance in percentage that an emerald is rewarded if at all.

Furthermore, i feel it should be chance per mob. example, `pigs=0.0000001` chance; `zombie=0.00001` chance; `squid=0.0` chance; `enderman=0.10` chance , and so on allowing us to configure every mob by our personal preference (with a `default=` if a mob is unspecified).

Please not: I am completely assuming my server's emerald rewards are offered via this plugin.  I do have other plugins that may be the rewarder -- i am unsure.

Thank you!

**Comment by jastice** [comment]
Gringotts does not alter item drops in any way, it only supplies an economy interface for whatever items you choose to make your server's currency. Please check your other plugins for one that awards money or items on kill.

**Comment by meoso** [comment]
Thank you, it was MobHunting in conjunction with Gringotts for anyone interested.  My gringotts was set for 0 decimal places, so MobHunting's reward was at minimum 1.0 money items which was Emeralds as per Gringott's default.
