### ISSUE TITLE
Gringotts /t deposit and [town vault] problems - needs high priority help

### ISSUE THREAD

**Issue by CandyManN** [MinecraftWars/Gringotts#132]
What steps will reproduce the problem?
1. /t deposit
2. Moneys are gone from inventory but not deposited into the Town bank.
3. If I try to create a town vault, as you can see below I paste you the console errors.

What is the expected output? What do you see instead?
Expected: [town vault] working chest.
Instead: nothing happens to the sign + errors in console. See below

What version of the product are you using?
Using Spigot Build 1.8.8 R.1/Latest Vault stable build and latest gringotts build (v2.7)
Using Towny 0.89.2.0

Do you have an error log of what happened?
http://pastebin.com/Gb7UQ6h3

Thank you.

**Comment by jastice** [comment]
Hi, is this on a new installation of Gringotts or has the server been around a while?

**Comment by CandyManN** [comment]
Loved your fast reply. You saved my day.
Aswell I do not have any data to lose (in Gringotts vaults). I just tried as I imagined from your reply to delete all and reinstall Gringotts. It worked now! Thank you again, sorry for wasting your time!

**Comment by jastice** [comment]
Glad that helped!
