### ISSUE TITLE
Gringotts & Towny

### ISSUE THREAD

**Issue by CainSeldon** [MinecraftWars/Gringotts#140]
Hey guys, I'm having an issue setting up Gringotts to work with Towny. I am using Towny for 1.7.10

I assume Towny is not seeing Gringotts, when I try to make a town, it says I have insufficient funds. I have the appropriate amount of emeralds on my person, as well as some in a vault.

Any thoughts? Im pretty new to both plugins so any suggestions would be great!
-Cain

**Comment by jastice** [comment]
Towny isn't directly aware of Gringotts. Instead, Gringotts integrates with Towny.
Have you checked https://github.com/MinecraftWars/Gringotts/wiki/Troubleshooting ?

**Comment by jastice** [comment]
Does it work for you?

**Comment by jastice** [comment]
Assumed obsolete, closing.
