### ISSUE TITLE
Several errors on Thermos Server 1.7.10

### ISSUE THREAD

**Issue by TomberWolf** [MinecraftWars/Gringotts#161]
Hey,

I get several errors with Gringotts. We're using Thermos (a current Cauldron fork) for 1.7.10, Vault 1.6.6 and Gringotts 2.9.

Please take a look at the loading error:
http://pastebin.com/085DjcVV

Strange: Vault detects Gringotts as active.

And the error for the /money command:
http://pastebin.com/Ayt5C1iC

**Comment by jastice** [comment]
It looks like Thermos might not contain the Ebean library, which Gringotts uses as default database backend. If that is the case, Gringotts might unfortunately be incompatible.

**Comment by TomPiXX** [comment]
As far as I can see, ebean should be included:
https://github.com/CyberdyneCC/Thermos/blob/master/build.gradle

Any chance to correct this or load this library externally?
Gringotts is a must-have plugin for us!

**Comment by TomPiXX** [comment]
Do you think you can fix that?

**Comment by jastice** [comment]
I'm afraid I don't really have the time these days. I'm happy to help out if you want to work on a fix.

**Comment by nikosgram13** [comment]
Hey @TomberWolf,

The Thermos has really different API than Bukkit and I really don't have the time to make Gringotts works with it.
