### ISSUE TITLE
Using iron_nuggets as denomination causes plugin to crash

### ISSUE THREAD

**Issue by Janzski** [MinecraftWars/Gringotts#168]
**Issue:**
All works fine until I try to add iron_nugget as a denomination. When I do, plugin doesn't seem to load, and if I try to type /money I get the following error in console:

https://pastebin.com/cm7HPZn4

**Server startup:**
https://pastebin.com/bCSLuWpw

**Gringotts config:** 
https://pastebin.com/10CNhAYn

**Gringotts messages:**
https://pastebin.com/MxAshQr2

Thanks for reading. Looking forward to using this awesome plugin!

**Comment by jastice** [comment]
I can't really look into this, but maybe it works if you use the numerical id for iron nugget?

**Comment by Janzski** [comment]
Just tried 452 instead of iron_nugget and I received this error: 

[10:56:36 ERROR]: [Gringotts] Encountered an error parsing currency. Please check your Gringotts configuration. Error was: null

**Comment by bundabrg** [comment]
I can't reproduce this so it may be resolved. Please comment if still an issue.
