### ISSUE TITLE
Gringott's dependency issue NoClassDefFound at Injector?

### ISSUE THREAD

**Issue by Litae** [MinecraftWars/Gringotts#169]
**_SOLVED. Ended up being Command GUI, added by someone secretly_**

We've been using Gringott's with Vault and Jobs for a week with no loss of function, but now Jobs is not paying out for any action. Examination of the logs finds this error: 

https://pastebin.com/EVVx1nAT

Any clue as to what is happening would be appreciated.

**Comment by VaiTon** [comment]
If you have found the solution please close the issue! :)
