### ISSUE TITLE
Depositing emeralds to Towny bank don't work

### ISSUE THREAD

**Issue by CheckeRr** [MinecraftWars/Gringotts#177]
When I type /town deposit 50, and in my inventory is 64 emeralds or 10 blocks, it don't work. If it's a emerald, it was stacking to blocks, when it's a blocks, I have message "you don't have enough money"

**Comment by nikosgram13** [comment]
Does your town region has an vault chest?

**Comment by CheckeRr** [comment]
Is it any possible to disable it? I want let players depositing without town vault

**Comment by OskarZyg** [comment]
What is the solution to this?
