### ISSUE TITLE
Vault Economy Problem

### ISSUE THREAD

**Issue by Bagsdto75** [MinecraftWars/Gringotts#180]
I Have an Issue with the Vault Plugin. The Balance is the Same For Every Player that Goes into any Gamemode. And Im Unable to Fix this Problem. The Economy Will Crash, Making Players Leave. There has to be Some Sort of Solution to Stop This Right?

**Comment by bundabrg** [comment]
I'm closing this as I've not noticed the problem. If this is still an issue please comment.
