### ISSUE TITLE
Error occurred while enabling Gringotts v2.10.1-SNAPSHOT (Is it up to date?)

### ISSUE THREAD

**Issue by Enzo41814** [MinecraftWars/Gringotts#183]
This error occurred in the following versions of Spigot and PaperSpigot (Paper):
Paper-1.13.2-b403.jar
spigot-1.13.2-R0.1-SNAPSHOT-b1966.jar

URL:
http://pasted.co/f943dd09

**Comment by nikosgram13** [comment]
What Vault version are you using?

**Comment by Enzo41814** [comment]
I'm using Vault 1.7.1 build 10 (https://ci.md-5.net/job/Vault/).

**Comment by Enzo41814** [comment]
For all those who use the 2.10.1-SNAPSHOT version of Gringotts and want to run it on a server 1.13.x I recommend using the version of Vault 1.6.7 build 6 (https://ci.md-5.net/job/Vault/6/) to be compatible.
It works perfect in the 1.13.2 server version!

**Comment by Enzo41814** [comment]
The only problem with that combination for 1.13.x are the items that don't detect them. 😞

**Comment by bundabrg** [comment]
I've got this running fine under 1.13.2 with Vault 1.7. It sounds like the version you're running is not supporting Vault 1.7 (Its looking for items, which was dropped from Vault 1.7).

Can you try my latest compile just in case you're running a slightly older version (I'm not 100% sure if the dev updates the version number as its a snapshot). https://github.com/bundabrg/Gringotts/releases

Run at your own risk. Otherwise check out the existing code and compile it to get the same binary.

**Comment by Enzo41814** [comment]
It works great in version 1.13! I would recommend updating the resource for the Spigot page by this. :smile: 

> says the issue was on line 121. In the older version this line dealt with Vault Items and was removed by this PR: #182

Yes, you're right. I had put vault 1.6.7 and then 1.6.10 because the latest plugin update in Spigot does not accept vault 1.7 at 1.13.

I'm using Paper-1.13.2-b455 and this works properly! (Your update).

**Comment by Enzo41814** [comment]
PS: Thank you very much for your help!

**Comment by bundabrg** [comment]
I think the slightly confusing thing is that the version on spigotmc is the same as the current build, but the one of spigotmc is the older version. Hopefully the dev see's this and uploads the correct version. For now I'll keep it maintained and push up PR's as needed.

Would you mind closing this issue if its working.

**Comment by Enzo41814** [comment]
Exactly! The only problem is that the API version 1.13 is not implemented in this last update.
There is no problem with closing this issue, thank you very much again! :smile:
