### ISSUE TITLE
2.11 snapshot not sending or receiving money

### ISSUE THREAD

**Issue by flanigomik** [MinecraftWars/Gringotts#193]
as the title says money can-not be sent or received in the beta build on paper 1.13.2 you can deposit and withdraw from your own vault but any attempt to make a payment results in the message 0.00 diamonds sent.

there are no errors in the log

**Comment by trianl2** [comment]
same thing here

**Comment by lvavila** [comment]
/money withdraw <amt? and /money deposit <amt> work but /money pay <amt> <player> does not resulting in above message.

**Comment by dorianxonic** [comment]
It looks like this project is abandoned.

**Comment by bundabrg** [comment]
I can confirm it. I'll check it out.
