### ISSUE TITLE
Commands just return the command root EG /player (money) (pay) etc and dont od anything

### ISSUE THREAD

**Issue by celestia369** [MinecraftWars/Gringotts#208]
All grongotts comands just return the info for them and vaults dont work

**Comment by bundabrg** [comment]
Which version of Gringotts and Minecraft?

**Comment by celestia369** [comment]
mincraft 1.12.2 and gringots 2.10 i think it may be a compatibiliyty error with the custom kist plugin.

**Comment by celestia369** [comment]
Confirmed its an incompatibility with the ckits plugin uninstalled gringots and the ckits plugin (which was broken when i installed Gringotts) started working and when i did it the other way round gringots started working again. do you know if there is a way to fix tbis r do i just have to choes one over the other?

**Comment by bundabrg** [comment]
In case it makes any difference can you try the version here: https://github.com/MinecraftWars/Gringotts/releases
