### ISSUE TITLE
/t deposit not working with gringotts

### ISSUE THREAD

**Issue by OskarZyg** [MinecraftWars/Gringotts#211]
Whenever I attempt to use /t deposit, Towny shows an error message:
[Towny] You don't have that much

This is very annoying as I can not deposit or expand my towns on the server.
Thank you!

**Comment by OskarZyg** [comment]
PS: I meant that I don’t want to make a Town Vault, like on EarthMC.

**Comment by bundabrg** [comment]
I think Gringotts philosophy was to always store items in some physical location.

**Comment by OskarZyg** [comment]
I know but is there a way to do it like EarthMC, without a town vault?

**Comment by bundabrg** [comment]
It has been asked a couple of times and specifically about town vaults. I assume you mean like a 'virtual' vault for the town where those with access can use it. A bit like how an Enderchest can be used as a 'virtual vault' for a player?

**Comment by fitz-y-y** [comment]
Bumping this issue a bit, I have the same "issue", I'd like to have a virtual vault rather than a physical location, it that possible?

**Comment by jastice** [comment]
Gringotts doesn't support fully virtual accounts, sorry!

**Comment by OskarZyg** [comment]
Any progress so far?

**Comment by jastice** [comment]
Probably somebody will need to take it upon themselves, as I'm no longer actively supporting Gringotts :(

**Comment by OskarZyg** [comment]
Stale, and whichever fork existed a year ago solved this.
