### ISSUE TITLE
Some of Towny Commands don't work with Gringotts

### ISSUE THREAD

**Issue by FlqmingPig** [MinecraftWars/Gringotts#217]
With Towny 0.96.1.0 in 1.13.2. For some reason, the /t and /n commands don't work with Gringotts. Yet when I remove Gringotts from the plugins folder, the commands work just fine. I tried the Gringotts versions of 2.10.1 to 2.11.0, still nothing. I will be grateful for a solution!

**Comment by FlqmingPig** [comment]
[Thu, 16. Apr 2020 19:52:56 GMT INFO] FlqmingPig issued server command: /t
[Thu, 16. Apr 2020 19:52:57 GMT WARN] [Towny] Plugin Towny v0.96.1.0-1.13.2 generated an exception while executing task 1004
[Thu, 16. Apr 2020 19:53:12 GMT INFO] FlqmingPig issued server command: /plugins
[Thu, 16. Apr 2020 19:53:24 GMT INFO] [dynmap] Loading default resource pack
[Thu, 16. Apr 2020 19:53:43 GMT INFO] FlqmingPig issued server command: /t
[Thu, 16. Apr 2020 19:53:44 GMT WARN] [Towny] Plugin Towny v0.96.1.0-1.13.2 generated an exception while executing task 1110
[Thu, 16. Apr 2020 19:53:44 GMT INFO] FlqmingPig issued server command: /n
[Thu, 16. Apr 2020 19:53:44 GMT WARN] [Towny] Plugin Towny v0.96.1.0-1.13.2 generated an exception while executing task 1113
[Thu, 16. Apr 2020 19:53:46 GMT INFO] FlqmingPig issued server command: /n ?
[Thu, 16. Apr 2020 19:53:52 GMT INFO] FlqmingPig issued server command: /n Georgia
[Thu, 16. Apr 2020 19:53:52 GMT WARN] [Towny] Plugin Towny v0.96.1.0-1.13.2 generated an exception while executing task 1129

almost forgot this

**Comment by Darklom** [comment]
Same issue as here - https://github.com/MinecraftWars/Gringotts/issues/214

He provides a pre-release version that fixes this
