### ISSUE TITLE
Modded Itens.

### ISSUE THREAD

**Issue by RafaelZ49** [MinecraftWars/Gringotts#229]
Hi, thats not a big issue, if possible can you support modded itens? cause im having troubles with a mod of coins, and tryed use these coins in gringotts and not worked. So can give me some help?

**Comment by nikosgram** [comment]
Hello :)

Gringotts is currently supports only Spigot and PaperMC. Which server software are you using?

**Comment by RafaelZ49** [comment]
i solved that.
