### ISSUE TITLE
Vault Towny Issue

### ISSUE THREAD

**Issue by LargoUsagi** [MinecraftWars/Gringotts#25]
I am trying to get this working on my server with towny.  I know it registers with vault because another plugin that uses the Vault API can add money to a player but Towny is consistantly saying I lack the funds to create a new town.

Love the plugin, its exactly what my server needed for an Econ plugin, love it.

Version infos:

Gringotts 1.3.0 
Vault 1.2.16-b184 
Towny 0.82.0.0
PermissionsEx 1.19.3

Thanks for any assistance you can provide

-Largo Usagi

**Comment by nikosgram** [comment]
## Triage outcome

Closing as obsolete. This report depends on the legacy Towny/Factions/WorldGuard account-holder integration, which has been intentionally removed from the current codebase (commit `dffb967`). It is therefore not a defect or deliverable for the maintained product. A future integration proposal should be filed as a new, current-version feature request with its supported API and compatibility scope.
