### ISSUE TITLE
[Town Vault] Disconnect

### ISSUE THREAD

**Issue by LargoUsagi** [MinecraftWars/Gringotts#31]
I logged into my MC server the other day and i was met with a notice that my town was going to be deleted due to lack of funds, checked the vault chest and there was plenty of emeralds in it.  i broke the sign and re attached it and it then said i had all of the emeralds again.

I don't know what could have happened there but I figure I would let you know.

-Largo

**Comment by nikosgram** [comment]
## Triage outcome

Closing as obsolete. This report depends on the legacy Towny/Factions/WorldGuard account-holder integration, which has been intentionally removed from the current codebase (commit `dffb967`). It is therefore not a defect or deliverable for the maintained product. A future integration proposal should be filed as a new, current-version feature request with its supported API and compatibility scope.
