### ISSUE TITLE
Town rename causes town vaults to be disconnected from town account in Towny

### ISSUE THREAD

**Issue by jastice** [MinecraftWars/Gringotts#34]
Perhaps there is a way to reference a town by id?

**Comment by nikosgram** [comment]
## Triage outcome

Closing as obsolete. This report depends on the legacy Towny/Factions/WorldGuard account-holder integration, which has been intentionally removed from the current codebase (commit `dffb967`). It is therefore not a defect or deliverable for the maintained product. A future integration proposal should be filed as a new, current-version feature request with its supported API and compatibility scope.
