### ISSUE TITLE
Methods to withdraw and deposit from vaults to inventory

### ISSUE THREAD

**Issue by jastice** [MinecraftWars/Gringotts#37]
Implement methods to withdraw from vaults to inventory:
- /money w <amount>
- ATM sign: right clicking withdraws an amount specified on the sign

Implement methods to deposit money from inventory to vaults:
- /money d <amount>
- ATM sign: right clicking deposits an amount specified on the sign

**Comment by lifehome** [comment]
May I know why these commands are missing?

**Comment by jastice** [comment]
The commands should be there, unless they are disabled in the configuration/permissions or something broke along the way

**Comment by lifehome** [comment]
Unfortunately this is what happened after the command has been executed, using version 2.10-SNAPSHOT from July 2017.
![2017-08-23_17 31 37](https://user-images.githubusercontent.com/1886237/29609179-f024b9ce-8828-11e7-822a-c84ca407f48f.png)
