### ISSUE TITLE
Please allow /town deposit to work

### ISSUE THREAD

**Issue by cecell** [MinecraftWars/Gringotts#47]
On my server we are using a bit of a hybrid physical/virtual currency for Towny.  For most if not all Towny servers i'm sure the [town vault] vault meets the needs perfectly.  However on our server we would prefer to use /town deposit as usual.  Currently when typing /town deposit # it deducts # from the players inventory but does not deposit the amount into either the town's bank or the town's vault.  Would you be willing to support this functionality?

If so it would be greatly appreciated!

**Comment by nikosgram** [comment]
## Triage outcome

Closing as obsolete. This report depends on the legacy Towny/Factions/WorldGuard account-holder integration, which has been intentionally removed from the current codebase (commit `dffb967`). It is therefore not a defect or deliverable for the maintained product. A future integration proposal should be filed as a new, current-version feature request with its supported API and compatibility scope.
