### ISSUE TITLE
can't use custom blocks from MoreMaterials/SpoutPlugin as currency

### ISSUE THREAD

**Issue by quarkbuddha** [MinecraftWars/Gringotts#66]
I tried to use a custom block defined with MoreMaterials as a currency, and strange things happened. Substance D (that's what the block is called) created by MoreMaterials wouldn't stack with Substance D added to my accout balance by Gringotts.

After a few seconds of looking at the MoreMaterials code, I strongly suspect that this is because if SpoutPlugin is present and being used the inventory add() method should be calling new SpoutItemStack() instead of new ItemStack().

I'm going to go ahead and implement this, because I really want it... would you be interested in the patch?

**Comment by jastice** [comment]
Did you get around to implementing it, or is it not an issue anymore?

**Comment by quarkbuddha** [comment]
No. Life interfered.
-- 
Mark Buda <hermit@acm.org>
I get my monkeys for nothing and my chimps for free.

**Comment by jastice** [comment]
Np, just updating my tickets :)
