### ISSUE TITLE
Towny - Async usage on vault causes Async errors in Gringotts

### ISSUE THREAD

**Issue by coaster3000** [MinecraftWars/Gringotts#88]
Gringotts is not thread safe...

I will attempt to get some stack traces... And more. Or I will attempt to fix it on my fork.

EDIT:

For all those that need an immediate fix you may use the latest towny version that.
Some of my pull reqs for several fixes have gone through. Including a temporary work around to this bug.

There is a new setting in the settings file under the economy section.

Which its default is this.
````
  use_async: 'true'
````

Setting it to false will force towny to be synchronise with the server thread thus the error will no longer occur.

````
  use_async: 'false'
````

**Comment by jastice** [comment]
So, at last, here's a dev version addressing this issue:
https://dl.dropboxusercontent.com/u/10988727/Gringotts-2.9-SNAPSHOT.jar

Would appreciate feedback on whether it works for you

**Comment by jastice** [comment]
I'll just go ahead and assume this works now ...
